apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx
  minReadySeconds: 10
  template:
    metadata:
      labels:
        k8s-app: nginx
        version: v1.0
    spec:
      containers:
      - name: nginx
        image: docker-host1.shef.ac.uk/alpine-nginx:latest
        ports:
        - containerPort: 80
     imagePullSecrets:
     - name: registrypullsecret
